version : 2

models:
  - name: stg_customers
    columns:
      - name : customer_id
        description : Customer ID
        tests :
          - unique
          - not_null
      - name : first_name
        description : Customers first name
        tests :
          - not_null
      - name : last_name
        description : Customers last name
        tests :
          - not_null
  - name: stg_orders
    columns:
      - name : order_id
        description : ID of order
        tests :
          - unique
          - not_null
      - name : customer_id
        description : Customers ID
        tests :
          - not_null
      - name : order_date
        description : Customers last name
        tests :
          - not_null
      - name : status
        description : Status of the order
        tests :
          - not_null
  - name: stg_payment
    columns:
      - name : id
        description : Payment ID
        tests :
          - unique
          - not_null
      - name : order_id
        description : Order's ID
        tests :
          - not_null
      - name : payment_method
        description : Way of paying the order
        tests :
          - not_null
      - name : total_amount_spent
        description : Total amount spent in USD
        tests :
          - not_null
      - name : payment_creation_date
        description : Payment creation date
        tests :
          - not_null

